# https://taskfile.dev
version: "3"

tasks:
  build:
    desc: "Build the provider binary"
    cmds:
      - go build -o terraform-provider-vercel
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - terraform-provider-vercel

  testacc:
    desc: "Run acceptance tests against the provider"
    env:
      TF_ACC: "true"
    cmds:
      - go test ./...

  install:
    desc: "Set up an override allowing a local version of the provider to be used"
    cmds:
      - cmd: |-
          cat << EOF > ~/.terraformrc
          provider_installation {
            dev_overrides {
              "vercel/vercel" = "$(pwd)"
            }
            direct {}
          }
          EOF

  uninstall:
    desc: "Remove any local overrides for local development"
    cmds:
      - rm ~/.terraformrc
